apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: replication.sofplicator.com
spec:
  group: sofplicator
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
          - kind
          - apiVersion
          - spec
          properties:
            kind:
              type: string
              enum:
                - replication
            apiVersion:
              type: string
              enum:
                - sofplicator.com/v1
            spec:
              type: object
              required:
              - targetRegistry
              - sourceRegistry
              properties:
                cronSpec:
                  type: string
                image:
                  type: string
                targetRegistry:
                  type: string
                sourceRegistry:
                  type: string
                replicationType:
                  type: string
                charts:
                  type: array
                  items:
                    type: object
                    required:
                    - name
                    - version
                    - repo
                    properties:
                      name:
                        type: string
                      version:
                        type: string
                      repo:
                        type: string
                images:
                  type: array
                  items:
                    type: object
                    required:
                    - name
                    - version
                    - repo
                    properties:
                      name:
                        type: string
                      version:
                        type: string
                      repo:
                        type: string
  scope: Namespaced
  names:
    plural: replications
    singular: replication
    kind: Replication
    shortNames:
    - repl