# permissions for end users to view replications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: replication-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sofplicator-controller
    app.kubernetes.io/part-of: sofplicator-controller
    app.kubernetes.io/managed-by: kustomize
  name: replication-viewer-role
rules:
- apiGroups:
  - sofplicator.com
  resources:
  - replications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sofplicator.com
  resources:
  - replications/status
  verbs:
  - get
